site_name: Pyprojectx

repo_url: https://github.com/pyprojectx/pyprojectx
edit_uri: edit/main/docs/docs
remote_name: https://github.com/pyprojectx/pyprojectx.github.io.git
remote_branch: main

theme:
  name: material
  palette:
    - scheme: default
      primary: white
  font:
    text: Open Sans
    code: Fira Code
  logo: assets/px.svg
  favicon: assets/px.svg
  custom_dir: overrides

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google

nav:
  - Home: index.md
  - Configuration:
    - config/tools.md
    - config/aliases.md
    - config/scripts.md
    - config/defaults.md
  - Usage: usage.md
  - Dev Dependencies: dev-dependencies.md
  - Recipes: recipes.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets
  - admonition
  - tables
  - toc:
      permalink: "#"
  - markdown_include.include:
      base_path: docs

copyright: Copyright &copy; 2020 <a href="https://upcycled-code.com/">Ivo Houbrechts</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pyprojectx/pyprojectx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IvoHoubrechts

extra_css: [assets/extra.css]
